services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "10001:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo_db:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "10002:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: items_db

  postgres_db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "10003:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  customer_service:
    build: ./customer_service
    container_name: customer_service_container
    restart: always
    ports:
      - "10004:8000"
    depends_on:
      - mysql_db
    volumes:
      - ./customer_service:/app
    environment:
      DATABASE_URL: mysql+pymysql://user:123456@mysql_db:3306/customer_db

volumes:
  mysql_data:
  mongo_data:
  postgres_data: